// Generated by CoffeeScript 1.6.3
var fs;

if (process.argv.length < 3) {
  return;
}

fs = require('fs');

fs.readFile(process.argv[2], {
  encoding: 'utf8'
}, function(err, data) {
  var array, line, _i, _len, _results;
  array = data.split('\n');
  _results = [];
  for (_i = 0, _len = array.length; _i < _len; _i++) {
    line = array[_i];
    _results.push(console.log(Buffer(line)));
  }
  return _results;
});
