// Generated by CoffeeScript 1.6.3
var map, stream, tr;

map = require('through2-map');

tr = require('trumpet')();

process.stdin.pipe(tr);

stream = tr.select('.loud').createStream();

stream.pipe(map(function(chunck) {
  return chunck.toString().toUpperCase();
})).pipe(stream);

tr.pipe(process.stdout);
