// Generated by CoffeeScript 1.6.3
var map, stream, tr;

map = require('through2-map');

tr = require('trumpet')();

stream = tr.select('.loud').createStream();

stream.pipe(map(function(chunck) {
  return chunck.toString().toUpperCase();
})).pipe(stream);

process.stdin.pipe(tr).pipe(process.stdout);
