// Generated by CoffeeScript 1.6.3
var crypto, uncrypto, untar, unzip;

untar = require('tar').Parse();

unzip = require('zlib').createGunzip();

crypto = require('crypto');

if (process.argv.length < 4) {
  return;
}

untar.on('entry', function(e) {
  var hash;
  if (e.type !== 'File') {
    return;
  }
  hash = crypto.createHash('md5', {
    encoding: 'hex'
  });
  hash.on('end', function() {
    return console.log(" " + e.path);
  });
  return e.pipe(hash).pipe(process.stdout);
});

uncrypto = crypto.createDecipher(process.argv[2], process.argv[3]);

process.stdin.pipe(uncrypto).pipe(unzip).pipe(untar);
