// Generated by CoffeeScript 1.6.3
var crypto, tr, uncrypto, untar, unzip;

untar = require('tar').Parse();

unzip = require('zlib').createGunzip();

crypto = require('crypto');

tr = require('through');

if (process.argv.length < 4) {
  return;
}

untar.on('entry', function(e) {
  if (e.type === 'File') {
    return e.pipe(crypto.createHash('md5', {
      encoding: 'hex'
    })).pipe(tr(null, function() {
      return this.queue(" " + e.path + "\n");
    })).pipe(process.stdout);
  }
});

uncrypto = crypto.createDecipher(process.argv[2], process.argv[3]);

process.stdin.pipe(uncrypto).pipe(unzip).pipe(untar);
