// Generated by CoffeeScript 1.6.3
var array16, array32;

if (process.argv.length < 3) {
  return;
}

array32 = new Uint32Array(1);

array32[0] = process.argv[2];

array16 = new Uint16Array(array32.buffer);

console.log(JSON.stringify(array16));
