// Generated by CoffeeScript 1.6.3
var bl;

bl = [];

process.stdin.resume();

process.stdin.on('data', function(buf) {
  return bl.push(buf);
});

process.stdin.on('end', function() {
  return console.log(Buffer.concat(bl));
});
