// Generated by CoffeeScript 1.6.3
var buf, i, nums, _i;

nums = [0, 15, 24, 3, 250, 83];

buf = new Buffer(6);

for (i = _i = 0; _i <= 5; i = ++_i) {
  buf.writeUInt8(nums[i], i);
}

console.log(buf.toString('hex'));
