// Generated by CoffeeScript 1.6.3
var fs;

if (process.argv.length < 3) {
  return;
}

fs = require('fs');

fs.readFile(process.argv[2], function(e, d) {
  var c, i, start, _i, _len;
  start = 0;
  for (i = _i = 0, _len = d.length; _i < _len; i = ++_i) {
    c = d[i];
    if (c === '\n'.charCodeAt(0)) {
      console.log(d.slice(start, i));
      start = i + 1;
    }
  }
  return console.log(d.slice(start));
});
