// Generated by CoffeeScript 1.6.3
process.stdin.on('data', function(buf) {
  var i, len, _i;
  len = buf.length - 1;
  for (i = _i = 0; 0 <= len ? _i <= len : _i >= len; i = 0 <= len ? ++_i : --_i) {
    if (buf[i] === 46) {
      buf.write('!', i);
    }
  }
  return console.log(buf);
});
