// Generated by CoffeeScript 1.6.3
process.stdin.on('data', function(buf) {
  var array, i, len, _i, _ref;
  len = buf.length;
  array = Uint8Array(ArrayBuffer(len));
  for (i = _i = 0, _ref = len - 1; 0 <= _ref ? _i <= _ref : _i >= _ref; i = 0 <= _ref ? ++_i : --_i) {
    array[i] = buf[i];
  }
  return console.log(JSON.stringify(array));
});
